### ISSUE TITLE
Use two different bucket for writing and reading

### ISSUE THREAD

**Issue by AurelienFT** [massalabs/stream_limiter#7]
For now we are using the same one it don't seems intuitive I think we should use two what do you think @litchipi ?

**Comment by litchipi** [comment]
Yeah sure, that makes perfect sense, and I'd push it even further, the buckets could be optional.
If the `ReadBucket` is `None`, then we read directly from the stream without any limit (same for write)

**Comment by AurelienFT** [comment]
Great idea !
